openapi: 3.0.3
info:
  title: Internal Ping-Pong Service
  version: 1.0.0
paths:
  /internal-ping:
    get:
      operationId: internal-ping
      tags:
        - internal-ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
